default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg

  - repo: https://gitlab.com/vojko.pribudic/pre-commit-update
    rev: v0.1.0
    hooks:
      - id: pre-commit-update

  - repo: local
    hooks:
      - id: rst-comment-cspell
        name: rst empty line before comment (GitHub rendering)
        language: pygrep # cSpell:ignore pygrep
        types:
          - rst
        args:
          - --multiline
        entry: "[^\\n]\\n\\.\\. cSpell:ignore"

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell # cSpell:ignore codespell
        additional_dependencies:
          - tomli # cSpell:ignore tomli

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.1.1
    hooks:
      - id: cspell

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.7
    hooks:
      - id: ruff
        args:
          # - With auto-fix, "ruff" should run before formatting tools.
          #   - https://docs.astral.sh/ruff/usage/#pre-commit
          - --fix
          - --show-fixes
          - --exit-non-zero-on-fix

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: no-commit-to-branch
        stages:
          - pre-commit
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          - css
          - javascript

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.0
    hooks:
      - id: black

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.5.3
    hooks:
      - id: pyproject-fmt # cSpell:ignore pyproject
        additional_dependencies:
          - tox>=4.9

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v1.6.1
  #  hooks:
  #    - id: mypy # cSpell:ignore mypy
  #      additional_dependencies:
  #        - PyQt6-stubs @ git+https://github.com/python-qt-tools/PyQt6-stubs@86d119e # - 2023-07-23

  - repo: local
    hooks:
      - id: pytest-check-headless
        name: pytest-check-headless
        language: system
        pass_filenames: false
        always_run: true
        entry: xvfb-run pytest # cSpell:ignore xvfb
        verbose: true

  - repo: local
    hooks:
      - id: coverage-badge
        stages:
          - pre-commit
        name: coverage-badge
        language: system
        pass_filenames: false
        always_run: true
        entry: coverage-badge -o assets/coverage.svg -f
        verbose: true

  - repo: local
    hooks:
      - id: scalene-profile
        name: scalene-profile
        language: system
        pass_filenames: false
        always_run: true
        entry:
          xvfb-run python3 -m scalene --no-browser --program-path src --cli --reduced-profile --- -m pytest --no-cov -k
          test_profile
        verbose: true
