version: "0.2"
ignorePaths:
  - .git/**
  - .github/disabled-workflows/
  - .gitignore
  - .taplo.toml
  - cspell.config.yaml
  - docs/
  - requirements{,-dev}.{txt,in}
dictionaryDefinitions: []
dictionaries: []
words:
  - Knopp
  - numpy
  - pylint
  - pyqt
  - pytest
  - pytz
  - RSLT
  - setuptools
  - sqlalchemy
ignoreWords: []
import: []
