version: "0.2"
ignorePaths:
  - .git/**
  - .github/disabled-workflows/
  - .gitignore
  - docs/
dictionaryDefinitions: []
dictionaries: []
words:
  - Knopp
  - numpy
  - pylint
  - pyqt
  - pytest
  - pytz
  - RSLT
  - setuptools
  - sqlalchemy
ignoreWords: []
import: []
