[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools",
  "wheel",
]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
preview = true
select = [
  "E", # - pycodestyle - Error # cSpell:ignore pycodestyle
  "W", # - pycodestyle - Warning
  "F", # - Pyflakes # cSpell:ignore Pyflakes
  "I", # - isort # cSpell:ignore isort
]
ignore = [
  "E203", # - whitespace-before-punctuation
]
