[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools",
  "wheel",
]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
target-version = "py310"
line-length = 100
preview = true
select = [
  "E",   # - pycodestyle - Error # cSpell:ignore pycodestyle
  "W",   # - pycodestyle - Warning
  "F",   # - Pyflakes # cSpell:ignore Pyflakes
  "I",   # - isort # cSpell:ignore isort
  "RUF", # - Ruff-specific rules
]
ignore = [
  "E203", # - whitespace-before-punctuation
]
