name: pre-commit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: tlambert03/setup-qt-libs@v1 # cSpell:ignore tlambert

      - name: Run local/setup-python-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: pre-commit-update,no-commit-to-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
